### PR TITLE
[WIP] Work on adding support for bundled constraints

### PR DESCRIPTION
**Pull request by morgante**

### CODE REVIEW

**Comment by briantkennedy** [comment]
Is this PR still in progress or actionable?

**Comment by morgante** [comment]
@briantkennedy Let's leave this open for me. I do plan to eventually build in some policy bundling for CFT Scorecard and this branch facilitates that.

**Comment by briantkennedy** [comment]
I see that we have a branch associated with this.  Can we close the PR for now as there's nothing actionable for a reviewer to do on this?

**Comment by morgante** [comment]
Sure, can close for now.

**Pull request closed without merging**
