### PR TITLE
Additional changes to support org policy & access context policy

### PR DESCRIPTION
**Pull request by katze120**
Complements https://github.com/forseti-security/config-validator/pull/137, for #136

### CODE REVIEW

**Comment by gkowalski-google** [comment]
@katze120 @briantkennedy Not sure if it's related to this PR, but I noticed the [CV build](https://pantheon.corp.google.com/cloud-build/builds/a14176c2-4752-428e-843b-034cd0882870;step=2?project=forseti-containers) failed and didn't produce an updated image.

**Comment by briantkennedy** [comment]
I don't have perms to view that page, but FCV seems to be building fine.

**Comment by katze120** [comment]
> @katze120 @briantkennedy Not sure if it's related to this PR, but I noticed the [CV build](https://pantheon.corp.google.com/cloud-build/builds/a14176c2-4752-428e-843b-034cd0882870;step=2?project=forseti-containers) failed and didn't produce an updated image.

Looks like the build is consistently failing since April due to timeout after 20mins. Step  `docker build -t gcv-proto-builder -f ./build/proto/Dockerfile .` takes 22 mins when I tested. Let me submit a PR to increase timeout to 30mins and see how that goes?

**Comment by briantkennedy** [comment]
sounds good

**Pull request merged**
