### PR TITLE
update google api library version

### PR DESCRIPTION
**Pull request by xingao267**

### CODE REVIEW

**Comment by xingao267** [comment]
@morgante @briantkennedy ptal, might fix https://github.com/forseti-security/policy-library/issues/367

**Comment by briantkennedy** [comment]
I have no problem with this, but I don't see any reason why it would fix that issue.  FCV processes data from the CAI dump, so if something isn't present, it's missing from the data being fed to FCV as FCV doesn't pull data from GCP.

**Comment by xingao267** [comment]
I'm not familiar with the code base and still trying to figure out how these things work together. From my understand, this update might change the library used in https://github.com/forseti-security/config-validator/blob/master/api/validator.proto#L46? and therefore change what fields get pulled out from CAI dump?

Do you have any other suggestions of how to fix https://github.com/forseti-security/policy-library/issues/367?

**Comment by morgante** [comment]
Agreed, I don't think just updating the API versions will do the trick. The asset proto [here](https://github.com/forseti-security/config-validator/blob/master/api/validator.proto#L31) will have to be updated as well.

**Comment by xingao267** [comment]
The audit_config is present in the CAI dump, but not in `input.asset.iam_policy` used by the policy library.

**Comment by morgante** [comment]
In that case, I think you'll need to get IAM team to update this published proto: https://github.com/forseti-security/config-validator/blob/master/api/validator.proto#L46

**Comment by xingao267** [comment]
Isn't that proto part of https://godoc.org/google.golang.org/api ?

**Comment by xingao267** [comment]
https://godoc.org/google.golang.org/api/iam/v1

**Comment by morgante** [comment]
@xingao267 No, I don't believe so. I think the protos are published separately (outside a particular client library).

**Comment by xingao267** [comment]
do you know how is the very of that proto specified?

**Comment by briantkennedy** [comment]
let's move discussion back to the issue page so it's not fragmented

**Pull request closed without merging**
